name: "MongoDB"
version: "7.0.8"
slug: "mongodb"
description: "A MongoDB addon for Home Assistant"
arch:
  - amd64
  - aarch64
  - armv7
startup: "services"
boot: "auto"
ports:
  27017/tcp: 27017
options:
  MONGO_INITDB_ROOT_USERNAME: null
  MONGO_INITDB_ROOT_PASSWORD: null
schema:
  MONGO_INITDB_ROOT_USERNAME: str
  MONGO_INITDB_ROOT_PASSWORD: password
image: "ghcr.io/cvele/hass-mongodb"
map:
  config:
    - source: /mnt/data/mongo
      target: /data/db
      type: rw
