profile: "hassio-supervisor"
path: "/usr/bin/mongod"

apparmor: true

cap_add:
  - NET_ADMIN
  - SYS_ADMIN

security_opt:
  - no-new-privileges:true
name: "MongoDB"
version: "4.4.16"
slug: "mongodb"
description: "A MongoDB addon for Home Assistant"
arch:
  - amd64
  - aarch64
startup: "services"
boot: "auto"
ports:
  27017/tcp: 27017
options:
  MONGO_INITDB_ROOT_USERNAME: null
  MONGO_INITDB_ROOT_PASSWORD: null
  MONGO_PORT: 27017
schema:
  MONGO_INITDB_ROOT_USERNAME: str
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_PORT: "int(1,65535)?"
image: "ghcr.io/cvele/hass-mongodb"
map:
  config:
    - source: /mnt/data/mongo
      target: /data/db
      type: rw
