name: "MongoDB"
version: "4.4.18"
slug: "mongodb"
description: "A MongoDB addon for Home Assistant"
arch:
  - amd64
  - aarch64
startup: "services"
boot: "auto"
ports:
  27017/tcp: 27017
options:
  MONGO_INITDB_ROOT_USERNAME: null
  MONGO_INITDB_ROOT_PASSWORD: null
  MONGO_PORT: 27017
  MONGO_BIND_IP: "0.0.0.0"
schema:
  MONGO_INITDB_ROOT_USERNAME: str
  MONGO_INITDB_ROOT_PASSWORD: str
  MONGO_PORT: "int(1,65535)?"
  MONGO_BIND_IP: "str?"
image: "ghcr.io/cvele/hass-mongodb"
map:
  config:
    - source: /mnt/data/mongo
      target: /data/db
      type: rw
