name: Lint
on: [pull_request]
jobs:
  lint:
    runs-on: self-hosted
    name: Lint Dockerfile and Shell Scripts
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: mongo4/Dockerfile
    - name: Run the sh-checker
      uses: luizm/action-sh-checker@v0.1.12
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHELLCHECK_OPTS: -e SC1004 # exclude some shellcheck warnings.
        SHFMT_OPTS: -s # arguments to shfmt.
      with:
        sh_checker_comment: true
