name: Release MongoDB

on:
  push:
    branches:
      - main
    paths:
      - 'mongodb/*'
      - '.github/workflows/release-mongodb.yml'
  workflow_dispatch:

jobs:
  release:
    name: Build and Push Docker Image
    runs-on: self-hosted
    strategy:
      matrix:
        platform: [amd64, arm64, armv7]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: mongodb
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: ghcr.io/cvele/hass-mongodb:7.0.8-${{ matrix.platform }},ghcr.io/cvele/hass-mongodb:latest-${{ matrix.platform }}
          build-args: |
            BUILD_FROM=${{ matrix.platform == 'amd64' && 'ghcr.io/home-assistant/amd64-base-ubuntu:20.04' || matrix.platform == 'arm64' && 'ghcr.io/home-assistant/aarch64-base-ubuntu:20.04' || matrix.platform == 'armv7' && 'ghcr.io/home-assistant/armv7-base-ubuntu:20.04' }}
            BUILD_ARCH=${{ matrix.platform }}
